name: get changes

on:
  workflow_call:
    outputs:
      conf_dev:
        value: ${{ jobs.get-changes.outputs.conf_dev }}

jobs:
  get-changes:
    name: detect tf workspaces modified
    runs-on: ubuntu-latest
    outputs:
      conf_dev: ${{ steps.get-dev-workspaces.outputs.workspaces }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Paths Changes Filter
        uses: dorny/paths-filter@v3.0.2
        id: changes
        with:
          list-files: json
          filters: |
            conf_dev:
                - added|modified: 'configuration/dev/**'
            conf_tst:
                - added|modified: 'configuration/tst/**'
            conf_acc:
                - added|modified: 'configuration/acc/**'
            conf_prd:
                - added|modified: 'configuration/prd/**'
            tfm:
                - 'terraform/**'
      - name: List dev workspaces
        uses: actions/github-script@v7
        id: get-dev-workspaces
        env:
          RETURN_ALL_WORKSPACES: ${{ steps.changes.outputs.tfm }}
          FILES_MODIFIED: ${{ steps.changes.outputs.conf_dev_files }}
          STAGE: dev
        with:
          script: |
            const { getallWorkspaces, filterWorkspace } = require('./scripts/shared-get-changes-functions.js')
            let workspaces  = []
            const returnAll = process.env.RETURN_ALL_WORKSPACES == 'true' 
            const stage     = process.env.STAGE

            if (returnAll) {
              workspaces = getallWorkspaces(stage)
            }else{
              const filesModified = JSON.parse(process.env.FILES_MODIFIED)
              workspaces = filterWorkspace(filesModified, stage)
            }

            console.log(`workspaces:`, workspaces)
            core.setOutput('workspaces', workspaces)
